// Generated by CoffeeScript 1.6.3
var EventEmitter, argv, commands, exec, exists, fs, optimist, path, spawn, usage, useWinPathSep, _, _ref;

fs = require("fs");

path = require('path');

_ = require('underscore');

_ref = require('child_process'), spawn = _ref.spawn, exec = _ref.exec;

EventEmitter = require('events').EventEmitter;

optimist = require('optimist');

commands = {
  "init": {
    command: "init",
    description: "Init current / specified directory with `hache` config."
  },
  "server": {
    command: "server",
    description: "Starts the `hache` instance."
  }
};

usage = "Hache\nUsage: hache [command]\n\nCommands:\n";

_.each(commands, function(command) {
  return usage += " [" + command.command + "] " + command.description + "\n";
});

argv = optimist.usage(usage).argv;

exists = fs.exists || path.exists;

useWinPathSep = path.sep === '\\';

exports.run = function() {
  if (!argv._.length) {
    optimist.showHelp();
  }
  if (argv._[0] === "init") {
    return require("./commands/init").run();
  }
  if (argv._[0] === "server") {
    return require("./commands/server").run();
  }
};
