ServerRoot: 
ServerName: "localhost"
ServerAlias: "*.localhost.dev"
ServerAdmin: admin@example.org
DocumentRoot: process.cwd()
Listen: 3000
User: nobody
Group: nobody
LoadModule:
AccessFileName: .htaccess
DirectoryIndex: "index.html index.htm index.php index.php4 index.php5"
ErrorLog: "logs/error_log"