// Generated by CoffeeScript 1.6.2
module.exports = {
  name: "init",
  description: "Initializes a new Hache environment within the directory.",
  options: [],
  usage: "init [name]",
  action: function(name) {
    return console.log("Initialized for " + name + "...");
  }
};
