// Generated by CoffeeScript 1.6.3
var Tail, config, fs, httpdBin, path, _;

fs = require("fs");

path = require("path");

_ = require("underscore");

Tail = require("tail").Tail;

config = require("../../config");

httpdBin = config.httpdBin;

exports.run = function() {
  var accessLog, cmd, errorLog, httpd;
  if (_.isEmpty(config.hache)) {
    console.error("`hache` config not found in this directory.\nPlease run `hache init` and try again.");
  } else {
    console.log("Starting `hache` server instance...");
  }
  console.log('Running apache at ' + config.hache.ServerName + ' on port ' + config.hache.Listen);
  errorLog = new Tail(path.join(process.cwd(), '.hache/logs/errors'));
  accessLog = new Tail(path.join(process.cwd(), '.hache/logs/access'));
  errorLog.on("line", function(data) {
    return console.error(data);
  });
  accessLog.on("line", function(data) {
    return console.log(data);
  });
  cmd = ["" + httpdBin + " -k start", "-f " + (path.join(process.cwd(), '.hache', 'httpd.conf')), '-e info', '-D FOREGROUND'];
  httpd = require('child_process').exec(cmd.join(" "));
  httpd.stdout.on('data', function(data) {
    return console.log(data);
  });
  httpd.stderr.on('data', function(data) {
    return console.log(data);
  });
  return httpd.on('close', function(code) {
    return console.log('httpd process exited with code ' + code);
  });
};
